language: php

env:
  global:
    - SYMFONY__db_host=localhost
    - SYMFONY__db_port=3306
    - SYMFONY__db_user=root
    - SYMFONY__db_password=""

php:
  - 5.4
  - 5.5

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE modera_activity_logger'